# Craig Tomkow
# Yaml file defining Google App environment

runtime: custom
env: flex

default_expiration: "1s"

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
