# Craig Tomkow
# Yaml file defining Google App environment

runtime: custom
env: flex

manual_scaling:
  instances: 1
  cpu: 1
  memory_gb: 0.6
  disk_size_gb: 10

default_expiration: "1s"

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
